Repository statisticsnorway/ssb-fagfunksjoner, pull requests merged in 2024-08, with the labels that each got.

#92 Remove duplicate license file
  LICENSE.md
Labels: documentation

#93 Expand versions, statistikkregister - debug v1.0.0 -> v1.0.1
  demos/all_combos_demo.py
  demos/statistikkregisteret.py
  demos/view_dataframe_demo.py
  pyproject.toml
  src/fagfunksjoner/__init__.py
  src/fagfunksjoner/api/statistikkregisteret.py
  src/fagfunksjoner/api/valuta.py
  src/fagfunksjoner/data/pandas_combinations.py
  src/fagfunksjoner/data/view_dataframe.py
  src/fagfunksjoner/paths/project_root.py
  src/fagfunksjoner/paths/versions.py
  src/fagfunksjoner/prodsone/check_env.py
  tests/api/test_statistikkregisteret.py
  tests/paths/test_get_next_version_number.py
  tests/paths/test_versions.py
Labels: bug, enhancement

#96 Fredrick wishes
  pyproject.toml
  src/fagfunksjoner/api/statistikkregisteret.py
  src/fagfunksjoner/data/datadok_extract.py
  tests/api/test_statistikkregisteret.py
  tests/data/test_datadoc_extract.py
  tests/paths/__init__.py
Labels: enhancement, refactoring
